name: Generate README Stats

on:
  schedule:
    - cron: "0 */6 * * *"   # updates every 6 hours
  workflow_dispatch:

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - uses: anuraghazra/github-readme-stats@master
